# image base
FROM python:3.8.5

# nuevo
# instalando dependencias
RUN apt-get update && \
    apt-get install -y gcc python3-dev libffi-dev libssl-dev && \
    apt-get install -y default-libmysqlclient-dev netcat-openbsd g++

#RUN apt install gcc python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev g++
# estableciendo direcetorio de trabajo
WORKDIR /usr/src/app

# agregando e instalando requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# nuevo
# agregando entrypoint.sh
COPY ./entrypoint-dev.sh /usr/src/app/entrypoint-dev.sh
RUN chmod +x /usr/src/app/entrypoint-dev.sh

# agregando app
COPY . /usr/src/app

# nuevo
# ejecutar server
#CMD ["/usr/src/app/entrypoint.sh"]
ENTRYPOINT  ["/usr/src/app/entrypoint-dev.sh"]
