version: '3.7'

services:

  token:
    build:
      context: ./services/token
      dockerfile: Dockerfile
    #volumes:
    #  - './services/users:/usr/src/app'
    #ports:
    #  - 5001:5000
    environment:
      #- FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.DevelopmentConfig  # nuevo
      - DATABASE_URL=mysql://user:password@token-db:3306/db  # nuevo
      - DATABASE_TEST_URL=mysql://user:password@token-db:3306/db  # nuevo

    depends_on:  # nuevo
      - token-db
    expose:
      - 5000

  token-db:  # nuevo
    build:
      context: ./services/token/project/db
      dockerfile: Dockerfile
    #ports:
    #  - 3306:3306
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    expose: 
      - 3306

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - token