version: '3.7'

services:

  token:
    build:
      context: ./services/token
      dockerfile: Dockerfile-dev
    volumes:
      - './services/token:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      #- FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig  # nuevo
      #- DATABASE_URL=postgres://postgres:postgres@token-db:5432/users_account_dev  # nuevo
      - DATABASE_URL=mysql://user:password@token-db:3306/db  # nuevo
      - DATABASE_TEST_URL=mysql://user:password@token-db:3306/db  # nuevo

    depends_on:  # nuevo
      - token-db

  token-db:  # nuevo Mysql
    build:
      context: ./services/token/project/db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=token-db
      - PMA_USER=user
      - PMA_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - token