version: '3.7'

services:

  token:
    build:
      context: ./services/token
      dockerfile: Dockerfile
    #volumes:
    #  - './services/users:/usr/src/app'
    #ports:
    #  - 5001:5000
    environment:
      #- FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.DevelopmentConfig  # nuevo
      - DATABASE_URL=mysql://isleep:Buenw1f1c4$A@aa50fi43w78xdt.c0xvoargw4wq.us-east-1.rds.amazonaws.com:3306/db  # nuevo
      - DATABASE_TEST_URL=mysql://isleep:Buenw1f1c4$A@aa50fi43w78xdt.c0xvoargw4wq.us-east-1.rds.amazonaws.com:3306/db  # nuevo
    expose:
      - 5000

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - token