version: '3.7'

services:

  token:
    build:
      context: ./services/token
      dockerfile: Dockerfile
    #volumes:
    #  - './services/users:/usr/src/app'
    #ports:
    #  - 5001:5000
    environment:
      #- FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.DevelopmentConfig  # nuevo
      - DATABASE_URL=mysql://${RDS_USERNAME}:${RDS_PASSWORD}@${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}  # nuevo
      - DATABASE_TEST_URL=mysql://${RDS_USERNAME}:${RDS_PASSWORD}@${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}  # nuevo
    expose:
      - 5000
      - 3306

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - token